### PR TITLE
Various indicator fixes

### PR DESCRIPTION
**Pull request by lordmortis**
This includes some basic changes i needed to do to make the `indicator_ha` example work properly for me. 

I'm not sure if the external memory thing for mbed_tls is a good idea or not, but until I did that - it wouldn't work in this project. This should address #48 

The day thing is just fixing up a copy-paste error i suspect!

### CODE REVIEW

**Comment by Love4yzp** [comment]
What's your IDF version?

**Comment by Love4yzp** [comment]
it works fine with me, when using the ha example with the internal mem.
if it works for you, LGTM, thanks for your contribution.

**Comment by lordmortis** [comment]
> What's your IDF version?

5.1 (I think? I just set everything up today on macOS. I’m pleased at how easy it all was!)

**Comment by lordmortis** [comment]
I wonder if it has something to do with MQTT not being setup properly yet… I have no idea if the other people in #48 had a not fully setup HA instance, but I haven’t gotten that far just yet.

**Comment by Love4yzp** [comment]
> I wonder if it has something to do with MQTT not being setup properly yet… I have no idea if the other people in #48 had a not fully setup HA instance, but I haven’t gotten that far just yet.

If the mqtt server is not accessible, the device can't connect to the server, it might display this message.
I tried server times. when i connected to the mqtt server that can't connect, it also came the error log.

**Comment by Love4yzp** [comment]
If you'd like, I created a new repo: https://github.com/Love4yzp/sensecap-indicator-ha
Also, there is somethings that I didn't done to modify the mqtt server address via the screen panel.

**Pull request merged**
